version: 2
jobs:
  frontend:
    working_directory: ~/ameliorate/frontend
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout: 
          path: ~/ameliorate
      - run:
          name: Setup Dependencies
          command: npm i
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Run Tests Coverage
          command: npm test -- --coverage
  # backend:
  #   working_directory: ~/ameliorate/backend
  #   docker:
  #     - image: circleci/node:8.12.0
  #   steps:
  #     - checkout: 
  #         path: ~/ameliorate
  #     - run:
  #         name: Setup Dependencies
  #         command: npm i
  #     - run:
  #         name: Run Tests
  #         command: npm test
# workflows:
#   version: 2
#   build_test_and_lint:
#     jobs:
#       - frontend
#       - backend
      # - test:
      #     requires:
      #     - hithere
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8.9
#     steps:
#       - checkout
#       - restore_cache: # special step to restore the dependency cache
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Setup Dependencies
#           command: npm install
#       - run:
#           name: Setup Code Climate test-reporter
#           command: |
#             curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
#             chmod +x ./cc-test-reporter
#       - save_cache: # special step to save the dependency cache
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
#       - run: # run tests
#           name: Run Test and Coverage
#           command: |
#             ./cc-test-reporter before-build
#             npm test -- --coverage
#             ./cc-test-reporter after-build --exit-code $?
